import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("shared communications schema is tenant scoped, source linked, recipient protected, and idempotent",()=>{const migration=source("supabase/migrations/20260904230000_dm3iqcm_communications_center.sql");assert.match(migration,/create table public\.notifications/);assert.match(migration,/organization_id uuid not null/);assert.match(migration,/recipient_user_id uuid not null/);assert.match(migration,/source_domain text not null/);assert.match(migration,/source_entity_id uuid not null/);assert.match(migration,/source_event_id uuid/);assert.match(migration,/unique \(organization_id, recipient_user_id, notification_type, source_domain, source_event_id\)/);assert.match(migration,/recipient_user_id=auth\.uid\(\)/);assert.match(migration,/public\.is_internal_member\(organization_id\)/);assert.match(migration,/revoke all on public\.notifications from public,anon,authenticated/);});

test("customer messages transactionally emit shared notifications to existing service-request recipients",()=>{const migration=source("supabase/migrations/20260904230000_dm3iqcm_communications_center.sql");const conversation=source("supabase/migrations/20260904180000_dm3iqcm_service_request_conversations.sql");assert.match(migration,/after insert on public\.service_request_messages/);assert.match(migration,/new\.author_type <> 'CUSTOMER'/);assert.match(migration,/request_row\.assigned_user_id/);assert.match(migration,/m\.role in \('BUSINESS_OWNER','BUSINESS_ADMIN'\)/);assert.match(migration,/public\.create_notification/);assert.match(migration,/new\.id/);assert.match(migration,/'\/service-desk\/' \|\| request_row\.id/);assert.match(conversation,/service request messages are immutable/);});

test("communications center exposes shared unread state and opens source through a read mutation",()=>{const page=source("app/communications/page.tsx");const actions=source("lib/data/communications-actions.ts");const repository=source("lib/data/communications-repository.ts");const shell=source("components/layout/app-shell.tsx");assert.match(page,/notification-item\$\{item\.read_at \? "" : " unread"\}/);assert.match(page,/openNotificationAction/);assert.match(page,/markAllNotificationsReadAction/);assert.match(actions,/set_notification_read_state/);assert.match(actions,/mark_all_notifications_read/);assert.match(repository,/getUnreadNotificationCount/);assert.match(shell,/href: "\/communications", label: "Communications"/);assert.match(shell,/nav-unread-count/);});

test("customer portal remains customer-safe and existing email delivery integration remains intact",()=>{const portal=source("app/portal/service-requests/[serviceRequestId]/page.tsx");const action=source("lib/data/customer-portal-actions.ts");assert.doesNotMatch(portal,/priority|Priority/);assert.match(action,/create_customer_service_request_message/);assert.match(action,/notifyStaffOfCustomerReply/);});
