import {
  AlertTriangle,
  ArrowLeft,
  Bell,
  Building,
  Building2,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleUserRound,
  Clock3,
  ClockAlert,
  ContactRound,
  FileQuestion,
  Headphones,
  LayoutDashboard,
  ListFilter,
  LogOut,
  Menu,
  Plus,
  Search,
  Settings,
  ShieldCheck,
  UserRoundCheck,
  UserRoundCog,
  UsersRound,
  X,
  Ban,
  BriefcaseBusiness,
  ClipboardCheck,
} from "lucide-react";

export const applicationIcons = {
  dashboard: LayoutDashboard,
  cases: BriefcaseBusiness,
  "service-desk": Headphones,
  communications: Bell,
  customers: ContactRound,
  tasks: ClipboardCheck,
  questions: FileQuestion,
  reports: ChartNoAxesColumnIncreasing,
  users: UsersRound,
  settings: Settings,
  account: CircleUserRound,
  "sign-out": LogOut,
  add: Plus,
  search: Search,
  filter: ListFilter,
  close: X,
  back: ArrowLeft,
  forward: ChevronRight,
  unread: Bell,
  due: Clock3,
  completed: CircleCheck,
  blocked: Ban,
  overdue: ClockAlert,
  organization: Building2,
  "organization-active": Building,
  platform: ShieldCheck,
  "user-active": UserRoundCheck,
  "user-pending": UserRoundCog,
  warning: AlertTriangle,
  menu: Menu,
  check: Check,
  status: Circle,
} as const;

export type ApplicationIconName = keyof typeof applicationIcons;
